# Generated by Django 4.2 on 2023-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_title',
            field=models.CharField(default='Default', max_length=10),
        ),
    ]
